### PR TITLE
Upgrade laminar to 0.13.0 version

### PR DESCRIPTION
**Pull request by mprevel**
Hi,

I was really happy to find this repository providing ready components.
Nonetheless, I encountered some issues when trying to use the component themes and this is due to an update of the laminar API I am using.
So this PR updates the laminar version to the current one.

This PR updates Laminar version to 0.12.2
It fixes the ReactiveStyle Style signature that has been updated.
It also updates sbt-scalajs to support this laminar version, and scalajs bundler accordingly.

The project version has not been changed and to ensure an easy use (without conflicts) should probably be set according to the laminar minor version.

The build itself should probably be updated to be standardized (it is currently hard to contribute) : 
- build.sbt is overwritten by a script
- github packages plugin requires having a key set or makes sbt fails to import the project
- requires ammonite
- requires scalafmt in command line or to find a workaround like I did (loading the subproject in IntelliJ and set the formatter to scalafmt) ; having it as an sbt plugin could avoid this problem
- material and showcase could be modules of a root project

Regards,

### CODE REVIEW

**Comment by raquo** [comment]
@mprevel Thanks!

Sorry for the inconvenient timing, but could you please bump Laminar version in this PR to 0.13.0? [Just released](https://laminar.dev/blog/2021/05/04/laminar-v0.13.0).

**Comment by mprevel** [comment]
@raquo I'll check that tonight :)

**Comment by mprevel** [comment]
Laminar version updated to 0.13.0

**Comment by silizza** [comment]
Hi!
Thank you for your job!

Are there any plans to merge this pull request and when?

**Pull request merged**
